#ifndef Telebot_MessageH
#define Telebot_MessageH

#include "User.h"
#include "Chat.h"
#include "Message.h"
#include "MessageEntity.h"
#include "Animation.h"
#include "Audio.h"
#include "Document.h"
#include "PhotoSize.h"
#include "Sticker.h"
#include "Video.h"
#include "VideoNote.h"
#include "Voice.h"
#include "Contact.h"
#include "Dice.h"
#include "Game.h"
#include "Poll.h"
#include "Venue.h"
#include "Location.h"
#include "MessageAutoDeleteTimerChanged.h"
#include "Invoice.h"
#include "SuccessfulPayment.h"
#include "UserShared.h"
#include "ChatShared.h"
#include "WriteAccessAllowed.h"
#include "PassportData.h"
#include "ProximityAlertTriggered.h"
#include "ForumTopicCreated.h"
#include "ForumTopicEdited.h"
#include "ForumTopicClosed.h"
#include "ForumTopicReopened.h"
#include "GeneralForumTopicHidden.h"
#include "GeneralForumTopicUnhidden.h"
#include "VideoChatScheduled.h"
#include "VideoChatStarted.h"
#include "VideoChatEnded.h"
#include "VideoChatParticipantsInvited.h"
#include "WebAppData.h"
#include "InlineKeyboardMarkup.h"

namespace Telebot
{
    class Message
    {
    public:
        typedef std::shared_ptr<Message> Ptr;

        std::int32_t MessageId;
        std::int32_t MessageThreadId;
        User::Ptr From;
        Chat::Ptr SenderChat;
        std::int32_t Ddate;
        Chat::Ptr Chat;
        User::Ptr ForwardFrom;
        Chat::Ptr ForwardFromChat;
        std::int32_t ForwardFromMessageId;
        std::string ForwardSignature;
        std::string ForwardSenderName;
        std::int32_t ForwardDate;
        bool IsTopicMessage;
        bool IsAutomaticForward;
        Message::Ptr ReplyToMessage;
        User::Ptr ViaBot;
        std::int32_t EditDate;
        bool HasProtectedContent;
        std::string MediaGroupId;
        std::string AuthorSignature;
        std::string Text;
        std::vector<MessageEntity::Ptr> Entities;
        Animation::Ptr Animation;
        Audio::Ptr Audio;
        Document::Ptr Document;
        std::vector<PhotoSize::Ptr> Photo;
        Sticker::Ptr Sticker;
        Video::Ptr Video;
        VideoNote::Ptr VideoNote;
        Voice::Ptr Voice;
        std::string Caption;
        std::vector<MessageEntity::Ptr> CaptionEntities;
        bool HasMediaSpoiler;
        Contact::Ptr Contact;
        Dice::Ptr Dice;
        Game::Ptr Game;
        Poll::Ptr Poll;
        Venue::Ptr Venue;
        Location::Ptr Location;
        std::vector<User::Ptr> NewChatMembers;
        User::Ptr LeftChatMember;
        std::string NewChatTitle;
        std::vector<PhotoSize::Ptr> NewChatPhoto;
        bool DeleteChatPhoto;
        bool GroupChatCreated;
        bool SupergroupChatCreated;
        bool ChannelChatCreated;
        MessageAutoDeleteTimerChanged::Ptr MessageAutoDeleteTimerChanged;
        std::int64_t MigrateToChatId;
        std::int64_t MigrateFromChatId;
        Message::Ptr PinnedMessage;
        Invoice::Ptr Invoice;
        SuccessfulPayment::Ptr SuccessfulPayment;
        UserShared::Ptr UserShared;
        ChatShared::Ptr ChatShared;
        std::string ConnectedWebsite;
        WriteAccessAllowed::Ptr WriteAccessAllowed;
        PassportData::Ptr PassportData;
        ProximityAlertTriggered::Ptr ProximityAlertTriggered;
        ForumTopicCreated::Ptr ForumTopicCreated;
        ForumTopicEdited::Ptr ForumTopicEdited;
        ForumTopicClosed::Ptr ForumTopicClosed;
        ForumTopicReopened::Ptr ForumTopicReopened;
        GeneralForumTopicHidden::Ptr GeneralForumTopicHidden;
        GeneralForumTopicUnhidden::Ptr GeneralForumTopicUnhidden;
        VideoChatScheduled::Ptr VideoChatScheduled;
        VideoChatStarted::Ptr VideoChatStarted;
        VideoChatEnded::Ptr VideoChatEnded;
        VideoChatParticipantsInvited::Ptr VideoChatParticipantsInvited;
        WebAppData::Ptr WebAppData;
        InlineKeyboardMarkup::Ptr ReplyMarkup;
    };
}

#endif